apiVersion: batch/v1
kind: CronJob
metadata:
  name: obs-file-cleanup-cron
  namespace: "{{ .Release.Namespace }}"
spec:
  schedule: "0 * * * *" # Every 60 minutes
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: file-cleanup
              image: "{{.Values.global.registry}}/{{.Values.global.repository}}/backend:{{ .Values.global.tag | default .Chart.AppVersion }}"
              args:
                - /bin/sh
                - -c
                - |
                  echo "Deleting files starting with obs- and older than 24 hours in /app/src/tempObsFiles"
                  ls
                  cd src
                  ls
                  cd tempObsFiles
                  ls
              volumeMounts:
              - name: obs-temp-files
                mountPath: /app/src/tempObsFiles
          restartPolicy: OnFailure
          volumes:
            - name: obs-temp-files
              persistentVolumeClaim:
                claimName: {{ regexReplaceAll "^bcgov/" .Release.Name "" }}-obs-temp-files-pvc
              